import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from '@/providers/ReactQueryProvider';
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="min-h-screen bg-zinc-900 text-white p-6">
          <div className="flex items-center justify-between mb-6">
              <a href="/dashboard"><h1 className="text-2xl font-bold">Uptime Stars Team - Hackaton</h1></a>
              <div className="flex items-center gap-4">
                  <Link
                      href="/monitors/new"
                      className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded"
                  >
                      + Add Monitor
                  </Link>
                  <Link
                      href="/dashboard"
                      className="text-sm underline hover:text-zinc-300"
                  >
                      Status Pages
                  </Link>
              </div>
          </div>
          <ReactQueryProvider>
              {children}
          </ReactQueryProvider>
      </div>
      </body>
    </html>
  );
}
